pipeline:
  name: sam-app
  identifier: samapp
  projectIdentifier: Serverless
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: Staging
        identifier: Staging
        description: ""
        type: Deployment
        spec:
          deploymentType: AWS_SAM
          service:
            serviceRef: helloworld
          environment:
            environmentRef: Staging
            deployToAll: false
            infrastructureDefinitions:
              - identifier: euwest1
          execution:
            steps:
              - stepGroup:
                  steps:
                    - step:
                        type: Background
                        name: dind
                        identifier: dind
                        spec:
                          connectorRef: account.harnessImage
                          image: docker:dind
                          shell: Sh
                          privileged: true
                        when:
                          stageStatus: Success
                        failureStrategies: []
                    - step:
                        type: DownloadManifests
                        name: DownloadManifests
                        identifier: DownloadManifests
                        spec: {}
                        timeout: 10m
                    - step:
                        type: AwsSamBuild
                        name: SAM Build
                        identifier: SAM_Build
                        spec:
                          connectorRef: account.harnessImage
                          image: harnessdev/sam-build:1.82.0-latest
                          imagePullPolicy: Always
                          buildCommandOptions:
                            - "--use-container"
                          samBuildDockerRegistryConnectorRef: account.harnessImage
                          envVariables: {}
                          privileged: false
                        when:
                          stageStatus: Success
                        timeout: 10m
                    - step:
                        type: AwsSamDeploy
                        name: SAM Deploy
                        identifier: SAM_Deploy
                        spec:
                          connectorRef: account.harnessImage
                          image: harnessdev/sam-deploy:1.82.0-latest
                          imagePullPolicy: Always
                          envVariables:
                            AWS_SESSION_TOKEN: <+secrets.getValue("acct. AWS_SESSION_TOKEN")'
                          stackName: mansong-sam
                        when:
                          stageStatus: Success
                        timeout: 10m
                  name: SAM Step Group
                  identifier: sam_step_group
                  sharedPaths:
                    - /var/run
                    - /var/lib/docker
                  stepGroupInfra:
                    type: KubernetesDirect
                    spec:
                      connectorRef: account.EKS
                      namespace: harness-deploy
                      labels: {}
                      annotations: {}
                      nodeSelector: {}
                      automountServiceAccountToken: true
                      tolerations: []
                      containerSecurityContext:
                        capabilities:
                          add: []
                          drop: []
                        privileged: true
                      os: Linux
                      hostNames: []
            rollbackSteps: []
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
